spring.application.name=FlightOnTimeAPI

# --- CONFIGURACI\uFFFDN DE H2 ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- DATASOURCE (CAMBIADO DE MEMORIA A ARCHIVO) ---
# Usamos AUTO_SERVER=TRUE para que Spring y Python puedan compartir el archivo
spring.datasource.url=jdbc:h2:file:./data/flightdb;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- JPA / HIBERNATE ---
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'update' permite que Hibernate cree las tablas de tus entidades si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURACI\uFFFDN ADICIONAL PARA EVITAR BLOQUEOS ---
# Esto asegura que la base de datos no se cierre inmediatamente si no hay conexiones activas
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10