# -*- coding: utf-8 -*-
"""flightontime_microservicio_ds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpFAj4w4a7JBz_7aF6u2oefT149d4v3N
"""




from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import pandas as pd

app = FastAPI(title="FlightOnTime Data Science Service")

model = joblib.load("modelo_XGB.joblib")
print("Modelo cargado correctamente")

# Cargar tabla de distancias
distancias_df = pd.read_csv("distancias.csv")
print("Tabla de distancias cargada")

class FlightRequest(BaseModel):
    aerolinea: str
    origen: str
    destino: str
    fecha_partida: str

def obtener_distancia(aerolinea, origen, destino):
    fila = distancias_df[
        (distancias_df["aerolinea"] == aerolinea) &
        (distancias_df["origin"] == origen) &
        (distancias_df["dest"] == destino)
    ]

    if fila.empty:
        raise ValueError("No se encontró la distancia para esa ruta")

    return float(fila.iloc[0]["distancia"])

from datetime import datetime

@app.post("/predict")
def predict_flight_delay(request: FlightRequest):

    # Convertir fecha_partida a datetime
    fecha = datetime.fromisoformat(request.fecha_partida)

    mes = fecha.month
    hora_salida = fecha.hour
    dia_semana = fecha.weekday()  # 0 = lunes

    # Obtener distancia desde el CSV
    try:
        distancia = obtener_distancia(
            request.aerolinea,
            request.origen,
            request.destino
        )
    except ValueError as e:
        return {"error": str(e)}

    # Crear DataFrame EXACTO que espera el modelo
    data = pd.DataFrame([{
        "aerolinea": request.aerolinea,
        "origin": request.origen,
        "dest": request.destino,
        "mes": mes,
        "hora_salida": hora_salida,
        "dia_semana": dia_semana,
        "distancia": distancia
    }])

    # Predicción de probabilidad (retraso = clase 1)
    prob_retraso = model.predict_proba(data)[0][1]

    # Decisión final
    resultado = "Retrasado" if prob_retraso >= 0.5 else "Puntual"

    # Respuesta EXACTA que espera el Back-End
    return {
        "prevision": resultado,
        "probabilidad": round(float(prob_retraso), 2)
    }

import sklearn
print(sklearn.__version__)

