spring.application.name=FlightOnTimeAPI

# --- CONFIGURACI\u00D3N POSTGRESQL ---
spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- LOGGING ---
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# --- POOL DE CONEXIONES ---
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

spring.h2.console.enabled=false

spring.security.user.name=admin
spring.security.user.password=admin123

ai.service.url=${AI_SERVICE_URL:http://localhost:8000}
