spring.application.name=FlightOnTimeAPI

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource persistente
spring.datasource.url=jdbc:h2:file:./data/flightdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging SQL completo
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Pool de conexiones
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
